### ISSUE TITLE
Feature request: Add variable to disable/enable primary display while streaming

### ISSUE THREAD

**Issue by Dude47** [fehbari/sunshine-scripts#13]
Is it possible to implement an optional boolean to make primary display disable itself if set to true on start stream and vice versa instead of setting up Virtual Display as main display?

**Comment by fehbari** [comment]
Unfortunately that's not very easy to do from a scripting perspective unless you can provide a known stable hardware ID or device name from your monitor. As you can imagine there's thousands of different ones out in the wild and each setup will have their own properties.

The reason we're able to do it for the virtual monitor is it has known properties determined by the VDD driver, so we can look it up reliably, and are thus able to enable / disable it automatically.

We're exploring adding a config file to store this kind of setting in, and that could optionally enable more advanced features. But in the meantime you can still accomplish what you're looking for rather easily.

If I understand correctly, what you're trying to do here is to automatically switch off your main display while streaming, then bring it back on. That's easy to achieve: _while streaming_, set the virtual monitor as the main display (per instructions), then press Windows key + P and select the option to only display in the primary monitor.

Now whenever you start streaming, the virtual monitor will be enabled and switched to as primary, and your physical monitor will go to sleep. When you stop streaming, the virtual monitor will be disabled and your physical display will wake back up as primary.

The reason this works is because Windows stores display preferences _per monitor arrangement_. When the virtual monitor is enabled, your monitor arrangement is virtual monitor + your physical displays. In that arrangement, you set the virtual display as primary and chose to only output video to it, so the physical ones can sleep. When the virtual monitor is disabled, your arrangement goes back to being only the physical displays, which has a different set of preferences, and Windows will make your physical the primary again and resume outputting video to it.

Just **beware** that doing this means if you forget to end the stream, when you come back to your computer the physical monitor will be blank. You'll either need to end the stream using your phone (or another device running Moonlight) or blindly hit Windows + P again to resume outputting to the physical display.

Related to the above, this is why I provide an optional failure recovery step. In the worst case scenario, you can power cycle your computer and all settings should revert to non-streaming mode. Another safeguard which I personally use is to have a tool that can execute commands on your computer over the network, like KDE connect. But that's a whole other set of steps you'll need to research if you're interested. :)

Hope that helps. Feel free to reach out if you need further help with this.

**Comment by Dude47** [comment]
Thank you for detailed response, setting "Show only on 2" (primary virtual display was numbered as 2 for me) while streaming did the trick!
